#include "thz/codegen.hpp"

#include <sstream>
#include <cstdio>
#include <cmath>
#include <algorithm>

namespace thz {

Codegen::Codegen(IRModule mod) : mod_(std::move(mod)) {
    for (auto& c : mod_.classes) classNames_.insert(c.name);
    for (auto& f : mod_.functions) fnNames_.insert(f.name);
    for (auto& g : mod_.globals) globalNames_.insert(g.first);
}

static std::string numLit(double v) {
    char buf[64];
    if (std::isnan(v)) return "std::nan(\"\")";
    std::snprintf(buf, sizeof buf, "%.17g", v);
    return buf;
}

std::string Codegen::cstr(const std::string& s) {
    std::string out = "\"";
    for (char ch : s) {
        switch (ch) {
        case '\\': out += "\\\\"; break;
        case '"':  out += "\\\""; break;
        case '\n': out += "\\n"; break;
        case '\r': out += "\\r"; break;
        case '\t': out += "\\t"; break;
        case '\0': out += "\\0"; break;
        default: out += ch; break;
        }
    }
    out += "\"";
    return out;
}

std::string Codegen::cppType(const TypeInfo& t) {
    switch (t.kind) {
    case T::Num:  return "double";
    case T::Str:  return "thz::String";
    case T::Bool: return "bool";
    case T::Void: return "void";
    case T::Array: return "thz::ArrayPtr";
    case T::Obj:
        if (!t.ref.empty() && isClass(t.ref)) return "std::shared_ptr<" + t.ref + ">";
        return "thz::ObjectPtr";
    case T::Fn:   return "thz::FuncPtr";
    case T::Null:
    case T::Any:
    default:      return "thz::Value";
    }
}

bool Codegen::isClass(const std::string& n) { return classNames_.count(n) > 0; }
bool Codegen::isFn(const std::string& n) { return fnNames_.count(n) > 0; }
bool Codegen::isGlobal(const std::string& n) { return globalNames_.count(n) > 0; }
bool Codegen::isTemp(const std::string& n) {
    return n.size() > 1 && n[0] == 't';
}

std::string Codegen::operand(const IROperand& o) {
    if (o.isConst) {
        switch (o.type.kind) {
        case T::Bool: return o.num != 0 ? "true" : "false";
        case T::Null: return "thz::Value()";
        case T::Str: return cstr(o.str);
        default: return numLit(o.num);
        }
    }
    if (o.name == "this") return "(*this)";
    return o.name;
}

std::string Codegen::tempDecls(const IRFn& f) {
    std::map<std::string, std::string> decls; // name -> type
    for (auto& l : f.locals) {
        auto& [name, t] = l;
        if (name == "this") continue;
        if (name == "super") continue;
        decls[name] = cppType(t);
    }
    for (auto& in : f.code) {
        if (!in.dst.empty() && in.dst != "this") {
            if (decls.count(in.dst) == 0) decls[in.dst] = cppType(in.type);
        }
    }
    std::string s;
    for (auto& [name, type] : decls) s += "    " + type + " " + name + ";\n";
    return s;
}

std::string Codegen::argList(const std::vector<IROperand>& args) {
    std::string s;
    for (size_t i = 0; i < args.size(); ++i) {
        if (i) s += ", ";
        s += operand(args[i]);
    }
    return s;
}

// map operator-> opcode for numOp: add=0 sub=1 mul=2 div=3 mod=4; cmp: lt=0 gt=1 le=2 ge=3 eq=4 ne=5

void Codegen::declareOp(const std::string& name, const TypeInfo& t) {
    (void)name; (void)t;
}

std::string Codegen::generate() {
    out_ = "// GENERATED BY thzc (JS -> C++)\n";
    out_ += "#include <memory>\n#include <vector>\n#include <map>\n#include <variant>\n";
    out_ += "#include <string>\n#include <cstdio>\n#include <cstdlib>\n#include <cmath>\n";
    out_ += "#include <stdexcept>\n#include <functional>\n#include <sstream>\n";
    out_ += "namespace thz {\n";
    out_ += runtimeHpp();
    out_ += "\n} // namespace thz\n\n";

    // user globals
    out_ += "namespace thz {\n";
    for (auto& g : mod_.globals) {
        out_ += cppType(g.second) + " " + g.first + ";\n";
    }
    out_ += "\n";

    for (auto& c : mod_.classes) {
        genClass(c);
    }
    for (auto& f : mod_.functions) {
        genFunction(f);
    }
    genMain(mod_.main);
    out_ += "\n} // namespace thz\n";

    out_ += "\nint main() { return thz::main(); }\n";
    return out_;
}

void Codegen::genFunction(const IRFn& f) {
    std::string sig = cppType(f.retType) + " " + f.name + "(";
    for (size_t i = 0; i < f.params.size(); ++i) {
        if (i) sig += ", ";
        sig += cppType(f.params[i].type) + " " + f.params[i].name;
    }
    sig += ")";
    out_ += "\n" + sig + " {\n";
    out_ += tempDecls(f);
    labelCounter_ = 0;
    for (auto& in : f.code) genIns(in);
    out_ += "}\n";
}

void Codegen::genMain(const IRFn& f) {
    out_ += "\nint main() {\n";
    out_ += tempDecls(f);
    labelCounter_ = 0;
    for (auto& in : f.code) genIns(in);
    out_ += "    return 0;\n}\n";
}

void Codegen::genClass(const IRClass& c) {
    out_ += "\nstruct " + c.name;
    if (!c.base.empty()) out_ += " : " + c.base;
    out_ += " {\n";
    for (auto& f : c.fields) {
        if (f.isStatic) continue;
        out_ += "    " + cppType(f.type) + " " + f.name + ";\n";
    }

    // constructor: default + field inits
    const IRFn* ctor = nullptr;
    for (auto& m : c.methods) if (m.isCtor) { ctor = &m; break; }

    std::string fieldInit;
    for (auto& f : c.fields) {
        if (!f.hasInit) continue;
        if (f.type.kind == T::Num) fieldInit += "        " + f.name + " = " + numLit(f.initNum) + ";\n";
        else if (f.type.kind == T::Str) fieldInit += "        " + f.name + " = " + cstr(f.initStr) + ";\n";
    }

    if (ctor) {
        std::string sig = "    " + c.name + "(";
        for (size_t i = 0; i < ctor->params.size(); ++i) {
            if (i) sig += ", ";
            sig += cppType(ctor->params[i].type) + " " + ctor->params[i].name;
        }
        sig += ")";
        out_ += sig + " {\n";
        out_ += fieldInit;
        labelCounter_ = 0;
        for (auto& in : ctor->code) {
            if (in.op == Op::Return) continue;
            if (in.op == Op::CallSuper) { out_ += "        " + (c.base.empty() ? std::string("") : c.base + "(" + argList(in.args) + ");") + "\n"; continue; }
            genIns(in);
        }
        out_ += "    }\n";
    } else {
        out_ += "    " + c.name + "() {\n" + fieldInit + "    }\n";
    }

    for (auto& m : c.methods) {
        if (m.isCtor) continue;
        std::string sig = m.isStatic ? "    static " : "    ";
        sig += cppType(m.retType) + " " + m.name + "(";
        for (size_t i = 0; i < m.params.size(); ++i) {
            if (i) sig += ", ";
            sig += cppType(m.params[i].type) + " " + m.params[i].name;
        }
        sig += ")";
        out_ += sig + " {\n";
        out_ += tempDecls(m);
        labelCounter_ = 0;
        for (auto& in : m.code) genIns(in);
        out_ += "    }\n";
    }
    out_ += "};\n";
}

void Codegen::genIns(const Ins& in) {
    switch (in.op) {
    case Op::Alloca: return;
    case Op::Label: out_ += "L" + std::to_string(in.label) + ":;\n"; return;
    case Op::Jump: out_ += "    goto L" + std::to_string(in.label) + ";\n"; return;
    case Op::JmpZ: {
        std::string cond;
        switch (in.a.type.kind) {
        case T::Num: cond = "!(" + operand(in.a) + ")"; break;
        case T::Str: cond = "(" + operand(in.a) + ").empty()"; break;
        case T::Bool: cond = "!(" + operand(in.a) + ")"; break;
        default: cond = "!thz::toBool(" + operand(in.a) + ")"; break;
        }
        out_ += "    if (" + cond + ") goto L" + std::to_string(in.label) + ";\n";
        return;
    }
    case Op::JmpNZ: {
        std::string cond;
        switch (in.a.type.kind) {
        case T::Num: cond = "(" + operand(in.a) + ") != 0"; break;
        case T::Str: cond = "!(" + operand(in.a) + ").empty()"; break;
        case T::Bool: cond = "(" + operand(in.a) + ")"; break;
        default: cond = "thz::toBool(" + operand(in.a) + ")"; break;
        }
        out_ += "    if (" + cond + ") goto L" + std::to_string(in.label) + ";\n";
        return;
    }
    case Op::Return:
        if (in.a.isConst && in.a.type.kind == T::Void) { out_ += "    return;\n"; return; }
        if (in.a.isConst && in.a.type.kind == T::Null) {
            out_ += "    return;\n";
            return;
        }
        out_ += "    return " + operand(in.a) + ";\n";
        return;
    case Op::Throw:
        out_ += "    throw std::runtime_error(thz::toString(" + operand(in.a) + "));\n";
        return;
    default:
        genExprIns(in);
        return;
    }
}

void Codegen::genExprIns(const Ins& in) {
    const bool dstVoid = cppType(in.type) == "void";

    switch (in.op) {
    case Op::Store: {
        std::string dt = cppType(in.type);
        std::string src = operand(in.a);
        if (dt == "void") { out_ += "    (void)(" + src + ");\n"; return; }
        std::string dst = in.dst;
        // coerce
        if (dt == "double") {
            if (in.a.type.kind != T::Num && !in.a.isConst) {
                src = "thz::toNumber(" + src + ")";
            } else if (in.a.isConst && in.a.type.kind != T::Num) {
                src = "thz::toNumber(" + src + ")";
            }
        } else if (dt == "thz::String" || dt == "std::string") {
            if (in.a.type.kind != T::Str) src = "thz::toString(" + src + ")";
        } else if (dt == "bool") {
            if (in.a.type.kind != T::Bool) src = "thz::toBool(" + src + ")";
        }
        out_ += "    " + dst + " = " + src + ";\n";
        return;
    }
    case Op::Const: {
        if (dstVoid) { out_ += "    (void)0;\n"; return; }
        out_ += "    " + in.dst + " = " + operand(in.a) + ";\n";
        return;
    }

    case Op::Add: {
        bool dyn = in.a.type.kind == T::Any || in.b.type.kind == T::Any ||
                   in.a.type.kind == T::Obj || in.b.type.kind == T::Obj ||
                   in.a.type.kind == T::Array || in.b.type.kind == T::Array ||
                   in.a.type.kind == T::Null || in.b.type.kind == T::Null;
        std::string expr;
        if (dyn) {
            if (in.type.kind == T::Str) expr = "thz::toString(thz::add(" + operand(in.a) + ", " + operand(in.b) + "))";
            else expr = "thz::toNumber(thz::add(" + operand(in.a) + ", " + operand(in.b) + "))";
        } else if (in.type.kind == T::Str) {
            expr = "thz::toString(" + operand(in.a) + ") + thz::toString(" + operand(in.b) + ")";
        } else {
            expr = operand(in.a) + " + " + operand(in.b);
        }
        out_ += "    " + in.dst + " = " + expr + ";\n";
        return;
    }
    case Op::Sub: case Op::Mul: case Op::Div: case Op::Mod: {
        bool dyn = in.a.type.kind == T::Any || in.b.type.kind == T::Any ||
                   in.a.type.kind == T::Obj || in.b.type.kind == T::Obj ||
                   in.a.type.kind == T::Array || in.b.type.kind == T::Array ||
                   in.a.type.kind == T::Null || in.b.type.kind == T::Null;
        int opc = in.op == Op::Sub ? 1 : in.op == Op::Mul ? 2 : in.op == Op::Div ? 3 : 4;
        std::string expr;
        if (dyn) expr = "thz::numOp(" + operand(in.a) + ", " + operand(in.b) + ", " + std::to_string(opc) + ")";
        else {
            std::string op = in.op == Op::Sub ? " - " : in.op == Op::Mul ? " * " : in.op == Op::Div ? " / " : " fmod(";
            if (in.op == Op::Mod) expr = "std::fmod(" + operand(in.a) + ", " + operand(in.b) + ")";
            else expr = operand(in.a) + op + operand(in.b);
        }
        out_ += "    " + in.dst + " = " + expr + ";\n";
        return;
    }
    case Op::Neg: out_ += "    " + in.dst + " = -thz::toNumber(" + operand(in.a) + ");\n"; return;
    case Op::Plus: out_ += "    " + in.dst + " = thz::toNumber(" + operand(in.a) + ");\n"; return;
    case Op::Not: out_ += "    " + in.dst + " = !thz::toBool(" + operand(in.a) + ");\n"; return;
    case Op::BitNot: out_ += "    " + in.dst + " = ~(long long)thz::toNumber(" + operand(in.a) + ");\n"; return;

    case Op::Lt: case Op::Gt: case Op::Le: case Op::Ge:
    case Op::Eq: case Op::Ne: case Op::StrictEq: case Op::StrictNe: {
        bool dyn = in.a.type.kind == T::Any || in.b.type.kind == T::Any ||
                   in.a.type.kind == T::Obj || in.b.type.kind == T::Obj ||
                   in.a.type.kind == T::Array || in.b.type.kind == T::Array;
        std::string expr;
        if (dyn || in.op == Op::StrictEq || in.op == Op::StrictNe) {
            int opc = 0;
            if (in.op == Op::Lt) opc = 0;
            else if (in.op == Op::Gt) opc = 1;
            else if (in.op == Op::Le) opc = 2;
            else if (in.op == Op::Ge) opc = 3;
            else if (in.op == Op::Eq) opc = 4;
            else if (in.op == Op::Ne) opc = 5;
            else if (in.op == Op::StrictEq) opc = 4;
            else opc = 5;
            if (in.op == Op::StrictEq) expr = "thz::strictEq(" + operand(in.a) + ", " + operand(in.b) + ")";
            else if (in.op == Op::StrictNe) expr = "!thz::strictEq(" + operand(in.a) + ", " + operand(in.b) + ")";
            else expr = "thz::cmp(" + operand(in.a) + ", " + operand(in.b) + ", " + std::to_string(opc) + ")";
        } else {
            std::string op;
            switch (in.op) {
            case Op::Lt: op = " < "; break;
            case Op::Gt: op = " > "; break;
            case Op::Le: op = " <= "; break;
            case Op::Ge: op = " >= "; break;
            case Op::Eq: op = " == "; break;
            default: op = " != "; break;
            }
            expr = operand(in.a) + op + operand(in.b);
        }
        out_ += "    " + in.dst + " = " + expr + ";\n";
        return;
    }

    case Op::BitAnd: case Op::BitOr: case Op::BitXor:
    case Op::Shl: case Op::Shr: {
        std::string op = in.op == Op::BitAnd ? " & " : in.op == Op::BitOr ? " | " : in.op == Op::BitXor ? " ^ " : in.op == Op::Shl ? " << " : " >> ";
        std::string expr = "(long long)thz::toNumber(" + operand(in.a) + ") " + op + " (long long)thz::toNumber(" + operand(in.b) + ")";
        out_ += "    " + in.dst + " = " + expr + ";\n";
        return;
    }

    case Op::GetField: {
        if (in.a.name == "Math") {
            out_ += "    " + in.dst + " = thz::mathFn(" + cstr(in.member) + ", {});\n";
            return;
        }
        if (in.a.type.kind == T::Obj && !in.a.type.ref.empty() && isClass(in.a.type.ref)) {
            out_ += "    " + in.dst + " = " + operand(in.a) + "->" + in.member + ";\n";
            return;
        }
        out_ += "    " + in.dst + " = thz::getMember(" + operand(in.a) + ", " + cstr(in.member) + ");\n";
        return;
    }
    case Op::SetField: {
        if (in.a.type.kind == T::Obj && !in.a.type.ref.empty() && isClass(in.a.type.ref)) {
            out_ += "    " + operand(in.a) + "->" + in.member + " = " + operand(in.b) + ";\n";
            return;
        }
        out_ += "    thz::setMember(" + operand(in.a) + ", " + cstr(in.member) + ", " + operand(in.b) + ");\n";
        return;
    }
    case Op::GetIndex:
        out_ += "    " + in.dst + " = thz::getIndex(" + operand(in.a) + ", " + operand(in.b) + ");\n";
        return;
    case Op::SetIndex:
        out_ += "    thz::setIndex(" + operand(in.a) + ", " + operand(in.b) + ", " + argList(in.args) + ");\n";
        return;

    case Op::NewArray:
        out_ += "    " + in.dst + " = thz::newArray();\n";
        return;
    case Op::ArraySpread: {
        std::string arr = operand(in.a);
        std::string src = operand(in.b);
        out_ += "    { auto& __items = (*std::get<thz::ArrayPtr>(" + src + ".data)).items; auto& __dst = (*std::get<thz::ArrayPtr>(" + arr + ".data)).items; __dst.insert(__dst.end(), __items.begin(), __items.end()); }\n";
        return;
    }
    case Op::NewObject:
        out_ += "    " + in.dst + " = thz::newObject();\n";
        return;
    case Op::ObjSpread:
        out_ += "    { for (auto& __kv : (*std::get<thz::ObjectPtr>(" + operand(in.b) + ".data)).props) (*std::get<thz::ObjectPtr>(" + operand(in.a) + ".data)).props[__kv.first] = __kv.second; }\n";
        return;

    case Op::Call: {
        std::string dst = in.dst;
        if (in.namedCall) {
            std::string call = in.a.name + "(" + argList(in.args) + ")";
            if (dstVoid) out_ += "    " + call + ";\n";
            else out_ += "    " + dst + " = " + call + ";\n";
            return;
        }
        std::string call = "thz::call(" + operand(in.a) + ", {" + argList(in.args) + "})";
        out_ += "    " + dst + " = " + call + ";\n";
        return;
    }
    case Op::CallNew: {
        if (in.namedCall && isClass(in.a.name)) {
            out_ += "    " + in.dst + " = std::make_shared<" + in.a.name + ">(" + argList(in.args) + ");\n";
            return;
        }
        out_ += "    " + in.dst + " = thz::call(" + operand(in.a) + ", {" + argList(in.args) + "});\n";
        return;
    }
    case Op::CallMember: {
        if (in.a.name == "console") {
            out_ += "    " + in.dst + " = thz::Value(thz::consoleLog({";
            out_ += argList(in.args);
            out_ += "}));\n";
            return;
        }
        if (in.a.name == "Math") {
            out_ += "    " + in.dst + " = thz::mathFn(" + cstr(in.member) + ", {" + argList(in.args) + "});\n";
            return;
        }
        if (in.member == "__push") {
            out_ += "    { auto& __i = (*std::get<thz::ArrayPtr>(" + operand(in.a) + ".data)).items; __i.push_back(" + argList(in.args) + "); }\n";
            return;
        }
        if (in.member == "__push_hole") {
            out_ += "    { auto& __i = (*std::get<thz::ArrayPtr>(" + operand(in.a) + ".data)).items; __i.push_back(thz::Value()); }\n";
            return;
        }
        if (in.member == "__length") {
            out_ += "    " + in.dst + " = (double)(*std::get<thz::ArrayPtr>(" + operand(in.a) + ".data)).items.size();\n";
            return;
        }
        if (in.member == "__typeof") {
            out_ += "    " + in.dst + " = thz::Value(thz::typeOf(" + argList(in.args) + "));\n";
            return;
        }
        if (in.member == "__instanceof_in_placeholder") {
            out_ += "    " + in.dst + " = thz::Value(thz::contains(" + operand(in.a) + ", " + argList(in.args) + "));\n";
            return;
        }
        if (in.isSuper) {
            std::string baseName;
            for (auto& c : mod_.classes) if (c.name == (in.a.type.ref.empty() ? "" : in.a.type.ref)) baseName = c.base;
            out_ += "    " + in.dst + " = this->" + baseName + "::" + in.member + "(" + argList(in.args) + ");\n";
            return;
        }
        if (in.a.type.kind == T::Obj && !in.a.type.ref.empty() && isClass(in.a.type.ref)) {
            out_ += "    " + in.dst + " = " + operand(in.a) + "->" + in.member + "(" + argList(in.args) + ");\n";
            return;
        }
        if (in.a.type.kind == T::Array) {
            out_ += "    " + in.dst + " = thz::callMember(" + operand(in.a) + ", " + cstr(in.member) + ", {" + argList(in.args) + "});\n";
            return;
        }
        out_ += "    " + in.dst + " = thz::callMember(" + operand(in.a) + ", " + cstr(in.member) + ", {" + argList(in.args) + "});\n";
        return;
    }

    case Op::MakeFn: {
        // find fn signature
        const IRFn* f = nullptr;
        for (auto& g : mod_.functions) if (g.name == in.member) { f = &g; break; }
        std::string body;
        if (!f) { out_ += "    " + in.dst + " = thz::Value();\n"; return; }
        std::string convArgs;
        for (size_t i = 0; i < f->params.size(); ++i) {
            if (i) convArgs += ", ";
            std::string t = cppType(f->params[i].type);
            if (t == "double") convArgs += "thz::toNumber(__a[" + std::to_string(i) + "])";
            else if (t == "thz::String" || t == "std::string") convArgs += "thz::toString(__a[" + std::to_string(i) + "])";
            else if (t == "bool") convArgs += "thz::toBool(__a[" + std::to_string(i) + "])";
            else convArgs += "__a[" + std::to_string(i) + "]";
        }
        std::string call = f->name + "(" + convArgs + ")";
        if (cppType(f->retType) == "void") {
            body = "        { " + call + "; }\n        return thz::Value();\n";
        } else if (cppType(f->retType) == "thz::Value") {
            body = "        return " + call + ";\n";
        } else {
            body = "        return thz::Value(" + call + ");\n";
        }
        out_ += "    " + in.dst + " = thz::Function::make(" + cstr(f->name) + ", [](const std::vector<thz::Value>& __a) -> thz::Value {\n";
        out_ += body;
        out_ += "    });\n";
        return;
    }
    case Op::CallSuper: {
        out_ += "    /* super ctor call */\n";
        return;
    }
    default:
        out_ += "    /* unhandled op */\n";
        return;
    }
}

const char* Codegen::runtimeHpp() {
    return R"RUNTIME(
using Number = double;
using String = std::string;

struct Array;
struct Object;
struct Function;
struct Value;

using ArrayPtr = std::shared_ptr<Array>;
using ObjectPtr = std::shared_ptr<Object>;
using FuncPtr = std::shared_ptr<Function>;

struct Array { std::vector<Value> items; };
struct Object { std::map<String, Value> props; };

using FnBody = std::function<Value(const std::vector<Value>&)>;

struct Function {
    String name;
    FnBody body;
    Function() = default;
    Function(String n, FnBody b) : name(std::move(n)), body(std::move(b)) {}
    static FuncPtr make(String n, FnBody b) { return std::make_shared<Function>(std::move(n), std::move(b)); }
};

struct Value {
    std::variant<std::monostate, Number, String, bool, ArrayPtr, ObjectPtr, FuncPtr> data;
    Value() : data(std::monostate{}) {}
    Value(Number n) : data(n) {}
    Value(String s) : data(std::move(s)) {}
    Value(const char* s) : data(String(s)) {}
    Value(bool b) : data(b) {}
    Value(ArrayPtr a) : data(std::move(a)) {}
    Value(ObjectPtr o) : data(std::move(o)) {}
    Value(FuncPtr f) : data(std::move(f)) {}
    Value(std::nullptr_t) : data(std::monostate{}) {}

    bool isNum() const { return std::holds_alternative<Number>(data); }
    bool isStr() const { return std::holds_alternative<String>(data); }
    bool isBool() const { return std::holds_alternative<bool>(data); }
    bool isUndef() const { return std::holds_alternative<std::monostate>(data); }
    bool isArr() const { return std::holds_alternative<ArrayPtr>(data); }
    bool isObj() const { return std::holds_alternative<ObjectPtr>(data); }
    bool isFn() const { return std::holds_alternative<FuncPtr>(data); }
};

inline Number toNumber(const Value& v) {
    if (auto* n = std::get_if<Number>(&v.data)) return *n;
    if (auto* b = std::get_if<bool>(&v.data)) return *b ? 1.0 : 0.0;
    if (auto* s = std::get_if<String>(&v.data)) {
        try { return std::stod(*s); } catch (...) { return std::nan(""); }
    }
    return 0;
}
inline bool toBool(const Value& v) {
    if (auto* b = std::get_if<bool>(&v.data)) return *b;
    if (auto* n = std::get_if<Number>(&v.data)) return *n != 0.0 && !std::isnan(*n);
    if (auto* s = std::get_if<String>(&v.data)) return !s->empty();
    return std::holds_alternative<ArrayPtr>(v.data) || std::holds_alternative<ObjectPtr>(v.data);
}
inline String toString(const Value& v) {
    if (auto* n = std::get_if<Number>(&v.data)) {
        if (std::isnan(*n)) return "NaN";
        if (std::floor(*n) == *n && std::abs(*n) < 1e15) {
            std::ostringstream os; os << (long long)*n; return os.str();
        }
        std::ostringstream os; os << *n; return os.str();
    }
    if (auto* s = std::get_if<String>(&v.data)) return *s;
    if (auto* b = std::get_if<bool>(&v.data)) return *b ? "true" : "false";
    return "undefined";
}
inline bool truthy(const Value& v) { return toBool(v); }

inline Value add(const Value& a, const Value& b) {
    if (a.isStr() || b.isStr()) return toString(a) + toString(b);
    return toNumber(a) + toNumber(b);
}
inline Number numOp(const Value& a, const Value& b, int op) {
    Number x = toNumber(a), y = toNumber(b);
    switch (op) {
    case 0: return x + y;
    case 1: return x - y;
    case 2: return x * y;
    case 3: return x / y;
    case 4: return std::fmod(x, y);
    default: return 0;
    }
}
inline bool cmp(const Value& a, const Value& b, int op) {
    if (a.isStr() && b.isStr()) {
        const String& x = std::get<String>(a.data);
        const String& y = std::get<String>(b.data);
        switch (op) {
        case 0: return x < y;
        case 1: return x > y;
        case 2: return x <= y;
        case 3: return x >= y;
        case 4: return x == y;
        default: return x != y;
        }
    }
    Number x = toNumber(a), y = toNumber(b);
    switch (op) {
    case 0: return x < y;
    case 1: return x > y;
    case 2: return x <= y;
    case 3: return x >= y;
    case 4: return x == y;
    default: return x != y;
    }
}
inline bool strictEq(const Value& a, const Value& b) {
    if (a.isNum() && b.isNum()) return std::get<Number>(a.data) == std::get<Number>(b.data);
    if (a.isStr() && b.isStr()) return std::get<String>(a.data) == std::get<String>(b.data);
    if (a.isBool() && b.isBool()) return std::get<bool>(a.data) == std::get<bool>(b.data);
    if (a.isArr() && b.isArr()) return std::get<ArrayPtr>(a.data) == std::get<ArrayPtr>(b.data);
    if (a.isObj() && b.isObj()) return std::get<ObjectPtr>(a.data) == std::get<ObjectPtr>(b.data);
    if (a.isUndef() && b.isUndef()) return true;
    return false;
}

inline Value newArray() { return std::make_shared<Array>(); }
inline Value newObject() { return std::make_shared<Object>(); }

inline Value getMember(const Value& self, const String& name) {
    if (auto* a = std::get_if<ArrayPtr>(&self.data)) {
        if (name == "length") return Value(Number((*a)->items.size()));
        if (name == "push") return Value(Function::make("push", [self](const std::vector<Value>& args) {
            auto& items = std::get<ArrayPtr>(self.data)->items;
            if (!args.empty()) items.push_back(args[0]);
            return Value(Number(items.size()));
        }));
        if (name == "pop") return Value(Function::make("pop", [self](const std::vector<Value>&) {
            auto* arr = std::get<ArrayPtr>(self.data).get();
            if (arr->items.empty()) return Value();
            Value v = arr->items.back(); arr->items.pop_back(); return v;
        }));
    }
    if (auto* o = std::get_if<ObjectPtr>(&self.data)) {
        auto it = (*o)->props.find(name);
        if (it != (*o)->props.end()) return it->second;
    }
    return Value();
}
inline void setMember(const Value& self, const String& name, const Value& v) {
    if (auto* o = std::get_if<ObjectPtr>(&self.data)) { (*o)->props[name] = v; return; }
    if (auto* a = std::get_if<ArrayPtr>(&self.data)) {
        if (name == "length") return;
    }
    throw std::runtime_error("cannot set property '" + name + "' on non-object");
}
inline Value getIndex(const Value& self, const Value& idx) {
    Number i = toNumber(idx);
    if (auto* a = std::get_if<ArrayPtr>(&self.data)) {
        long long ii = (long long)i;
        if (ii >= 0 && (size_t)ii < (*a)->items.size()) return (*a)->items[ii];
        return Value();
    }
    if (auto* o = std::get_if<ObjectPtr>(&self.data)) {
        auto it = (*o)->props.find(toString(idx));
        if (it != (*o)->props.end()) return it->second;
    }
    return Value();
}
inline void setIndex(const Value& self, const Value& idx, const Value& v) {
    Number i = toNumber(idx);
    if (auto* a = std::get_if<ArrayPtr>(&self.data)) {
        long long ii = (long long)i;
        if ((size_t)ii >= (*a)->items.size()) (*a)->items.resize((size_t)ii + 1);
        (*a)->items[ii] = v;
        return;
    }
    if (auto* o = std::get_if<ObjectPtr>(&self.data)) { (*o)->props[toString(idx)] = v; return; }
    throw std::runtime_error("cannot index non-container");
}

inline Value call(const Value& fn, const std::vector<Value>& args) {
    if (auto* f = std::get_if<FuncPtr>(&fn.data)) {
        if ((*f)->body) return (*f)->body(args);
    }
    throw std::runtime_error("attempted to call a non-function value");
}
inline Value callMember(const Value& self, const String& name, const std::vector<Value>& args) {
    Value m = getMember(self, name);
    if (m.isFn()) return call(m, args);
    throw std::runtime_error("'" + name + "' is not a function");
}

inline String typeOf(const Value& v) {
    if (v.isNum()) return "number";
    if (v.isStr()) return "string";
    if (v.isBool()) return "boolean";
    if (v.isFn()) return "function";
    if (v.isArr()) return "object";
    if (v.isObj()) return "object";
    return "undefined";
}

inline bool contains(const Value& container, const Value& item) {
    if (auto* a = std::get_if<ArrayPtr>(&container.data)) {
        for (auto& x : (*a)->items) if (strictEq(x, item)) return true;
        return false;
    }
    if (auto* o = std::get_if<ObjectPtr>(&container.data)) {
        return (*o)->props.count(toString(item)) > 0;
    }
    return false;
}

inline void consoleLog(const std::vector<Value>& args) {
    for (size_t i = 0; i < args.size(); ++i) {
        if (i) std::printf(" ");
        if (auto* a = std::get_if<ArrayPtr>(&args[i].data)) {
            std::printf("[");
            for (size_t k = 0; k < (*a)->items.size(); ++k) {
                if (k) std::printf(", ");
                std::printf("%s", toString((*a)->items[k]).c_str());
            }
            std::printf("]");
            continue;
        }
        if (auto* o = std::get_if<ObjectPtr>(&args[i].data)) {
            std::printf("{ ");
            bool first = true;
            for (const auto& kv : (*o)->props) {
                if (!first) std::printf(", ");
                first = false;
                std::printf("%s: %s", kv.first.c_str(), toString(kv.second).c_str());
            }
            std::printf(" }");
            continue;
        }
        std::printf("%s", toString(args[i]).c_str());
    }
    std::printf("\n");
}

inline Value mathFn(const String& name, const std::vector<Value>& args) {
    Number x = args.empty() ? 0.0 : toNumber(args[0]);
    Number y = args.size() > 1 ? toNumber(args[1]) : 0.0;
    if (name == "floor") return Value(std::floor(x));
    if (name == "ceil") return Value(std::ceil(x));
    if (name == "round") return Value(std::round(x));
    if (name == "abs") return Value(std::fabs(x));
    if (name == "sqrt") return Value(std::sqrt(x));
    if (name == "pow") return Value(std::pow(x, y));
    if (name == "min") { Number m = x; for (size_t i = 1; i < args.size(); ++i) m = std::min(m, toNumber(args[i])); return Value(m); }
    if (name == "max") { Number m = x; for (size_t i = 1; i < args.size(); ++i) m = std::max(m, toNumber(args[i])); return Value(m); }
    if (name == "random") return Value(Number(std::rand() / (double)RAND_MAX));
    if (name == "PI") return Value(3.141592653589793);
    if (name == "E") return Value(2.718281828459045);
    return Value();
}
)RUNTIME";
}

} // namespace thz